package care.smith.top.backend.service.datasource;

import static org.junit.jupiter.api.Assertions.assertEquals;

import care.smith.top.backend.AbstractTest;
import care.smith.top.backend.model.jpa.datasource.EncounterDao;
import care.smith.top.backend.model.jpa.datasource.SubjectDao;
import care.smith.top.backend.model.jpa.datasource.SubjectResourceDao;
import care.smith.top.top_document_query.util.DateUtil;
import java.io.Reader;
import java.io.StringReader;
import java.math.BigDecimal;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;

@SpringBootTest
@ContextConfiguration
class FHIRImportTest extends AbstractTest {
  String dataSourceId = "data_source_1";

  @Test
  void testImportMedicationFirst() {
    String fhir =
        "{\r\n"
            + "  \"resourceType\" : \"Bundle\",\r\n"
            + "  \"id\" : \"101\",\r\n"
            + "  \"type\" : \"collection\",\r\n"
            + "  \"entry\" : [\r\n"
            //
            + "{\r\n"
            + "  \"resource\" : {\r\n"
            + "  \"resourceType\": \"Encounter\",\r\n"
            + "  \"id\": \"e2\",\r\n"
            + "  \"text\": {\r\n"
            + "    \"status\": \"generated\",\r\n"
            + "    \"div\": \"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">Encounter with patient @example who is at home</div>\"\r\n"
            + "  },\r\n"
            + "  \"contained\": [\r\n"
            + "    {\r\n"
            + "      \"resourceType\": \"Location\",\r\n"
            + "      \"id\": \"home\",\r\n"
            + "      \"description\": \"Client's home\",\r\n"
            + "      \"mode\": \"kind\"\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"status\": \"finished\",\r\n"
            + "  \"class\": {\r\n"
            + "    \"system\": \"http://terminology.hl7.org/CodeSystem/v3-ActCode\",\r\n"
            + "    \"code\": \"HH\",\r\n"
            + "    \"display\": \"home health\"\r\n"
            + "  },\r\n"
            + "  \"subject\": {\r\n"
            + "    \"reference\": \"Patient/p2\"\r\n"
            + "  },\r\n"
            + "  \"participant\": [\r\n"
            + "    {\r\n"
            + "      \"period\": {\r\n"
            + "        \"start\": \"2015-01-17T16:00:00+10:00\",\r\n"
            + "        \"end\": \"2015-01-17T16:30:00+10:00\"\r\n"
            + "      },\r\n"
            + "      \"individual\": {\r\n"
            + "        \"reference\": \"Practitioner/example\",\r\n"
            + "        \"display\": \"Dr Adam Careful\"\r\n"
            + "      }\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"period\": {\r\n"
            + "    \"start\": \"2015-01-17T16:00:00+10:00\",\r\n"
            + "    \"end\": \"2015-01-17T16:30:00+10:00\"\r\n"
            + "  },\r\n"
            + "  \"location\": [\r\n"
            + "    {\r\n"
            + "      \"location\": {\r\n"
            + "        \"reference\": \"#home\",\r\n"
            + "        \"display\": \"Client's home\"\r\n"
            + "      },\r\n"
            + "      \"status\": \"completed\",\r\n"
            + "      \"period\": {\r\n"
            + "        \"start\": \"2015-01-17T16:00:00+10:00\",\r\n"
            + "        \"end\": \"2015-01-17T16:30:00+10:00\"\r\n"
            + "      }\r\n"
            + "    }\r\n"
            + "  ]\r\n"
            + "}},"
            //
            + "{\r\n"
            + "  \"resource\" : {\r\n"
            + "  \"resourceType\": \"Encounter\",\r\n"
            + "  \"id\": \"e1\",\r\n"
            + "  \"text\": {\r\n"
            + "    \"status\": \"generated\",\r\n"
            + "    \"div\": \"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">Encounter with patient @example</div>\"\r\n"
            + "  },\r\n"
            + "  \"status\": \"in-progress\",\r\n"
            + "  \"class\": {\r\n"
            + "    \"system\": \"http://terminology.hl7.org/CodeSystem/v3-ActCode\",\r\n"
            + "    \"code\": \"IMP\",\r\n"
            + "    \"display\": \"inpatient encounter\"\r\n"
            + "  },\r\n"
            + "  \"subject\": {\r\n"
            + "    \"reference\": \"Patient/p1\"\r\n"
            + "  }\r\n"
            + "  }\r\n"
            + "}\r\n,"
            //
            + "{\r\n"
            + "  \"resource\" : {\r\n"
            + "  \"resourceType\": \"Patient\",\r\n"
            + "  \"id\": \"p2\",\r\n"
            + "  \"text\": {\r\n"
            + "    \"status\": \"generated\",\r\n"
            + "    \"div\": \"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">\\n      \\n      <p>Patient Simon Notsowell @ Acme Healthcare, Inc. MR = 123457, DECEASED</p>\\n    \\n    </div>\"\r\n"
            + "  },\r\n"
            + "  \"identifier\": [\r\n"
            + "    {\r\n"
            + "      \"use\": \"usual\",\r\n"
            + "      \"type\": {\r\n"
            + "        \"coding\": [\r\n"
            + "          {\r\n"
            + "            \"system\": \"http://terminology.hl7.org/CodeSystem/v2-0203\",\r\n"
            + "            \"code\": \"MR\"\r\n"
            + "          }\r\n"
            + "        ]\r\n"
            + "      },\r\n"
            + "      \"system\": \"urn:oid:0.1.2.3.4.5.6.7\",\r\n"
            + "      \"value\": \"123457\"\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"active\": true,\r\n"
            + "  \"name\": [\r\n"
            + "    {\r\n"
            + "      \"use\": \"official\",\r\n"
            + "      \"family\": \"Notsowell\",\r\n"
            + "      \"given\": [\r\n"
            + "        \"Simon\"\r\n"
            + "      ]\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"gender\": \"male\",\r\n"
            + "  \"birthDate\": \"1982-01-23\",\r\n"
            + "  \"deceasedDateTime\": \"2015-02-14T13:42:00+10:00\",\r\n"
            + "  \"managingOrganization\": {\r\n"
            + "    \"reference\": \"Organization/1\",\r\n"
            + "    \"display\": \"ACME Healthcare, Inc\"\r\n"
            + "  }\r\n"
            + "  }\r\n"
            + "}\r\n,"
            //
            + "{\r\n"
            + "  \"resource\" : {\r\n"
            + "  \"resourceType\": \"Patient\",\r\n"
            + "  \"id\": \"p1\",\r\n"
            + "  \"text\": {\r\n"
            + "    \"status\": \"generated\",\r\n"
            + "    \"div\": \"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">\\n\\t\\t\\t<table>\\n\\t\\t\\t\\t<tbody>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Name</td>\\n\\t\\t\\t\\t\\t\\t<td>Peter James \\n              <b>Chalmers</b> (&quot;Jim&quot;)\\n            </td>\\n\\t\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Address</td>\\n\\t\\t\\t\\t\\t\\t<td>534 Erewhon, Pleasantville, Vic, 3999</td>\\n\\t\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Contacts</td>\\n\\t\\t\\t\\t\\t\\t<td>Home: unknown. Work: (03) 5555 6473</td>\\n\\t\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Id</td>\\n\\t\\t\\t\\t\\t\\t<td>MRN: 12345 (Acme Healthcare)</td>\\n\\t\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\t</tbody>\\n\\t\\t\\t</table>\\n\\t\\t</div>\"\r\n"
            + "  },\r\n"
            + "  \"identifier\": [\r\n"
            + "    {\r\n"
            + "      \"use\": \"usual\",\r\n"
            + "      \"type\": {\r\n"
            + "        \"coding\": [\r\n"
            + "          {\r\n"
            + "            \"system\": \"http://terminology.hl7.org/CodeSystem/v2-0203\",\r\n"
            + "            \"code\": \"MR\"\r\n"
            + "          }\r\n"
            + "        ]\r\n"
            + "      },\r\n"
            + "      \"system\": \"urn:oid:1.2.36.146.595.217.0.1\",\r\n"
            + "      \"value\": \"12345\",\r\n"
            + "      \"period\": {\r\n"
            + "        \"start\": \"2001-05-06\"\r\n"
            + "      },\r\n"
            + "      \"assigner\": {\r\n"
            + "        \"display\": \"Acme Healthcare\"\r\n"
            + "      }\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"active\": true,\r\n"
            + "  \"name\": [\r\n"
            + "    {\r\n"
            + "      \"use\": \"official\",\r\n"
            + "      \"family\": \"Chalmers\",\r\n"
            + "      \"given\": [\r\n"
            + "        \"Peter\",\r\n"
            + "        \"James\"\r\n"
            + "      ]\r\n"
            + "    },\r\n"
            + "    {\r\n"
            + "      \"use\": \"usual\",\r\n"
            + "      \"given\": [\r\n"
            + "        \"Jim\"\r\n"
            + "      ]\r\n"
            + "    },\r\n"
            + "    {\r\n"
            + "      \"use\": \"maiden\",\r\n"
            + "      \"family\": \"Windsor\",\r\n"
            + "      \"given\": [\r\n"
            + "        \"Peter\",\r\n"
            + "        \"James\"\r\n"
            + "      ],\r\n"
            + "      \"period\": {\r\n"
            + "        \"end\": \"2002\"\r\n"
            + "      }\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"telecom\": [\r\n"
            + "    {\r\n"
            + "      \"use\": \"home\"\r\n"
            + "    },\r\n"
            + "    {\r\n"
            + "      \"system\": \"phone\",\r\n"
            + "      \"value\": \"(03) 5555 6473\",\r\n"
            + "      \"use\": \"work\",\r\n"
            + "      \"rank\": 1\r\n"
            + "    },\r\n"
            + "    {\r\n"
            + "      \"system\": \"phone\",\r\n"
            + "      \"value\": \"(03) 3410 5613\",\r\n"
            + "      \"use\": \"mobile\",\r\n"
            + "      \"rank\": 2\r\n"
            + "    },\r\n"
            + "    {\r\n"
            + "      \"system\": \"phone\",\r\n"
            + "      \"value\": \"(03) 5555 8834\",\r\n"
            + "      \"use\": \"old\",\r\n"
            + "      \"period\": {\r\n"
            + "        \"end\": \"2014\"\r\n"
            + "      }\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"gender\": \"male\",\r\n"
            + "  \"birthDate\": \"1974-12-25\",\r\n"
            + "  \"_birthDate\": {\r\n"
            + "    \"extension\": [\r\n"
            + "      {\r\n"
            + "        \"url\": \"http://hl7.org/fhir/StructureDefinition/patient-birthTime\",\r\n"
            + "        \"valueDateTime\": \"1974-12-25T14:35:45-05:00\"\r\n"
            + "      }\r\n"
            + "    ]\r\n"
            + "  },\r\n"
            + "  \"deceasedBoolean\": false,\r\n"
            + "  \"address\": [\r\n"
            + "    {\r\n"
            + "      \"use\": \"home\",\r\n"
            + "      \"type\": \"both\",\r\n"
            + "      \"text\": \"534 Erewhon St PeasantVille, Rainbow, Vic  3999\",\r\n"
            + "      \"line\": [\r\n"
            + "        \"534 Erewhon St\"\r\n"
            + "      ],\r\n"
            + "      \"city\": \"PleasantVille\",\r\n"
            + "      \"district\": \"Rainbow\",\r\n"
            + "      \"state\": \"Vic\",\r\n"
            + "      \"postalCode\": \"3999\",\r\n"
            + "      \"period\": {\r\n"
            + "        \"start\": \"1974-12-25\"\r\n"
            + "      }\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"contact\": [\r\n"
            + "    {\r\n"
            + "      \"relationship\": [\r\n"
            + "        {\r\n"
            + "          \"coding\": [\r\n"
            + "            {\r\n"
            + "              \"system\": \"http://terminology.hl7.org/CodeSystem/v2-0131\",\r\n"
            + "              \"code\": \"N\"\r\n"
            + "            }\r\n"
            + "          ]\r\n"
            + "        }\r\n"
            + "      ],\r\n"
            + "      \"name\": {\r\n"
            + "        \"family\": \"du Marché\",\r\n"
            + "        \"_family\": {\r\n"
            + "          \"extension\": [\r\n"
            + "            {\r\n"
            + "              \"url\": \"http://hl7.org/fhir/StructureDefinition/humanname-own-prefix\",\r\n"
            + "              \"valueString\": \"VV\"\r\n"
            + "            }\r\n"
            + "          ]\r\n"
            + "        },\r\n"
            + "        \"given\": [\r\n"
            + "          \"Bénédicte\"\r\n"
            + "        ]\r\n"
            + "      },\r\n"
            + "      \"telecom\": [\r\n"
            + "        {\r\n"
            + "          \"system\": \"phone\",\r\n"
            + "          \"value\": \"+33 (237) 998327\"\r\n"
            + "        }\r\n"
            + "      ],\r\n"
            + "      \"address\": {\r\n"
            + "        \"use\": \"home\",\r\n"
            + "        \"type\": \"both\",\r\n"
            + "        \"line\": [\r\n"
            + "          \"534 Erewhon St\"\r\n"
            + "        ],\r\n"
            + "        \"city\": \"PleasantVille\",\r\n"
            + "        \"district\": \"Rainbow\",\r\n"
            + "        \"state\": \"Vic\",\r\n"
            + "        \"postalCode\": \"3999\",\r\n"
            + "        \"period\": {\r\n"
            + "          \"start\": \"1974-12-25\"\r\n"
            + "        }\r\n"
            + "      },\r\n"
            + "      \"gender\": \"female\",\r\n"
            + "      \"period\": {\r\n"
            + "        \"start\": \"2012\"\r\n"
            + "      }\r\n"
            + "    }\r\n"
            + "  ],\r\n"
            + "  \"managingOrganization\": {\r\n"
            + "    \"reference\": \"Organization/1\"\r\n"
            + "  }\r\n"
            + "  }\r\n"
            + "}\r\n,"
            //
            + "  {\r\n"
            + "    \"fullUrl\" : \"https://example.com/base/Observation/r15\",\r\n"
            + "    \"resource\" : {\r\n"
            + "      \"resourceType\" : \"Observation\",\r\n"
            + "      \"id\" : \"r15\",\r\n"
            + "      \"text\" : {\r\n"
            + "        \"status\" : \"generated\",\r\n"
            + "        \"div\" : \"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\"><p class=\\\"res-header-id\\\"><b>Generated Narrative: Observation r15</b></p><a name=\\\"r15\\\"> </a><a name=\\\"hcr15\\\"> </a><a name=\\\"r15-en-US\\\"> </a><p><b>status</b>: final</p><p><b>code</b>: <span title=\\\"Codes:{http://loinc.org 711-2}\\\">Eosinophils</span></p><p><b>subject</b>: <a href=\\\"patient-example-b.html\\\">Duck D Donald (official) other, DoB Unknown ( Medical record number\\u00a0(use:\\u00a0usual,\\u00a0))</a></p><p><b>performer</b>: <a href=\\\"organization-example-lab.html\\\">Acme Laboratory, Inc</a></p><p><b>value</b>: 0.92 x10*9/L<span style=\\\"background: LightGoldenRodYellow\\\"> (Details: UCUM  code10*9/L = '10*9/L')</span></p><p><b>interpretation</b>: <span title=\\\"Codes:{http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation HH}\\\">Critical high</span></p><h3>ReferenceRanges</h3><table class=\\\"grid\\\"><tr><td style=\\\"display: none\\\">-</td><td><b>Low</b></td><td><b>High</b></td></tr><tr><td style=\\\"display: none\\\">*</td><td>0.04 x10*9/L<span style=\\\"background: LightGoldenRodYellow\\\"> (Details: UCUM  code10*9/L = '10*9/L')</span></td><td>0.40 x10*9/L<span style=\\\"background: LightGoldenRodYellow\\\"> (Details: UCUM  code10*9/L = '10*9/L')</span></td></tr></table></div>\"\r\n"
            + "      },\r\n"
            + "      \"status\" : \"final\",\r\n"
            + "      \"code\" : {\r\n"
            + "        \"coding\" : [{\r\n"
            + "          \"system\" : \"http://loinc.org\",\r\n"
            + "          \"code\" : \"711-2\",\r\n"
            + "          \"display\" : \"Eosinophils [#/volume] in Blood by Automated count\"\r\n"
            + "        }],\r\n"
            + "        \"text\" : \"Eosinophils\"\r\n"
            + "      },\r\n"
            + "      \"subject\" : {\r\n"
            + "        \"reference\" : \"Patient/p1\"\r\n"
            + "      },\r\n"
            + "      \"performer\" : [{\r\n"
            + "        \"reference\" : \"Organization/1832473e-2fe0-452d-abe9-3cdb9879522f\",\r\n"
            + "        \"display\" : \"Acme Laboratory, Inc\"\r\n"
            + "      }],\r\n"
            + "      \"encounter\": {\r\n"
            + "        \"reference\": \"Encounter/e1\"\r\n"
            + "      },\r\n"
            + "      \"valueQuantity\" : {\r\n"
            + "        \"value\" : 0.92,\r\n"
            + "        \"unit\" : \"x10*9/L\",\r\n"
            + "        \"system\" : \"http://unitsofmeasure.org\",\r\n"
            + "        \"code\" : \"10*9/L\"\r\n"
            + "      },\r\n"
            + "      \"interpretation\" : [{\r\n"
            + "        \"coding\" : [{\r\n"
            + "          \"system\" : \"http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation\",\r\n"
            + "          \"code\" : \"HH\"\r\n"
            + "        }]\r\n"
            + "      }],\r\n"
            + "      \"referenceRange\" : [{\r\n"
            + "        \"low\" : {\r\n"
            + "          \"value\" : 0.04,\r\n"
            + "          \"unit\" : \"x10*9/L\",\r\n"
            + "          \"system\" : \"http://unitsofmeasure.org\",\r\n"
            + "          \"code\" : \"10*9/L\"\r\n"
            + "        },\r\n"
            + "        \"high\" : {\r\n"
            + "          \"value\" : 0.40,\r\n"
            + "          \"unit\" : \"x10*9/L\",\r\n"
            + "          \"system\" : \"http://unitsofmeasure.org\",\r\n"
            + "          \"code\" : \"10*9/L\"\r\n"
            + "        }\r\n"
            + "      }]\r\n"
            + "    }\r\n"
            + "  },\r\n"
            //
            + "  {\r\n"
            + "    \"fullUrl\" : \"https://example.com/base/Observation/r17\",\r\n"
            + "    \"resource\" : {\r\n"
            + "      \"resourceType\" : \"Observation\",\r\n"
            + "      \"id\" : \"r17\",\r\n"
            + "      \"text\" : {\r\n"
            + "        \"status\" : \"generated\",\r\n"
            + "        \"div\" : \"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\"><p class=\\\"res-header-id\\\"><b>Generated Narrative: Observation r17</b></p><a name=\\\"r17\\\"> </a><a name=\\\"hcr17\\\"> </a><a name=\\\"r17-en-US\\\"> </a><p><b>status</b>: final</p><p><b>code</b>: <span title=\\\"Codes:{http://loinc.org 704-7}\\\">Basophils</span></p><p><b>subject</b>: <a href=\\\"patient-example-b.html\\\">Duck D Donald (official) other, DoB Unknown ( Medical record number\\u00a0(use:\\u00a0usual,\\u00a0))</a></p><p><b>performer</b>: <a href=\\\"organization-example-lab.html\\\">Acme Laboratory, Inc</a></p><p><b>value</b>: 0.92 x10*9/L<span style=\\\"background: LightGoldenRodYellow\\\"> (Details: UCUM  code10*9/L = '10*9/L')</span></p><h3>ReferenceRanges</h3><table class=\\\"grid\\\"><tr><td style=\\\"display: none\\\">-</td><td><b>High</b></td></tr><tr><td style=\\\"display: none\\\">*</td><td>0.21 x10*9/L<span style=\\\"background: LightGoldenRodYellow\\\"> (Details: UCUM  code10*9/L = '10*9/L')</span></td></tr></table></div>\"\r\n"
            + "      },\r\n"
            + "      \"status\" : \"final\",\r\n"
            + "      \"code\" : {\r\n"
            + "        \"coding\" : [{\r\n"
            + "          \"system\" : \"http://loinc.org\",\r\n"
            + "          \"code\" : \"704-7\",\r\n"
            + "          \"display\" : \"Basophils [#/volume] in Blood by Automated count\"\r\n"
            + "        }],\r\n"
            + "        \"text\" : \"Basophils\"\r\n"
            + "      },\r\n"
            + "      \"subject\" : {\r\n"
            + "        \"reference\" : \"Patient/p2\"\r\n"
            + "      },\r\n"
            + "      \"performer\" : [{\r\n"
            + "        \"reference\" : \"Organization/1832473e-2fe0-452d-abe9-3cdb9879522f\",\r\n"
            + "        \"display\" : \"Acme Laboratory, Inc\"\r\n"
            + "      }],\r\n"
            + "      \"encounter\": {\r\n"
            + "        \"reference\": \"Encounter/e2\"\r\n"
            + "      },\r\n"
            + "      \"valueQuantity\" : {\r\n"
            + "        \"value\" : 0.12,\r\n"
            + "        \"unit\" : \"x10*9/L\",\r\n"
            + "        \"system\" : \"http://unitsofmeasure.org\",\r\n"
            + "        \"code\" : \"10*9/L\"\r\n"
            + "      },\r\n"
            + "      \"referenceRange\" : [{\r\n"
            + "        \"high\" : {\r\n"
            + "          \"value\" : 0.21,\r\n"
            + "          \"unit\" : \"x10*9/L\",\r\n"
            + "          \"system\" : \"http://unitsofmeasure.org\",\r\n"
            + "          \"code\" : \"10*9/L\"\r\n"
            + "        }\r\n"
            + "      }]\r\n"
            + "    }\r\n"
            + "  }]\r\n"
            + "}";

    Reader reader = new StringReader(fhir);

    FHIRImport imp =
        new FHIRImport(
            dataSourceId,
            reader,
            subjectRepository,
            encounterRepository,
            subjectResourceRepository);
    imp.run();

    SubjectDao sub1 =
        new SubjectDao(dataSourceId, "Patient/p1", DateUtil.parse("1974-12-25"), "male");
    SubjectDao sub2 =
        new SubjectDao(dataSourceId, "Patient/p2", DateUtil.parse("1982-01-23"), "male");

    EncounterDao enc1 = new EncounterDao(dataSourceId, "Encounter/e1", sub1).type("IMP");
    EncounterDao enc2 =
        new EncounterDao(
            dataSourceId,
            "Encounter/e2",
            sub2,
            "HH",
            DateUtil.parse("2015-01-17T07:00"),
            DateUtil.parse("2015-01-17T07:30"));

    SubjectResourceDao res1 =
        new SubjectResourceDao(
                dataSourceId, "Observation/r15", sub1, enc1, "http://loinc.org", "711-2")
            .numberValue(new BigDecimal("0.92"))
            .unit("x10*9/L");
    SubjectResourceDao res2 =
        new SubjectResourceDao(
                dataSourceId, "Observation/r17", sub2, enc2, "http://loinc.org", "704-7")
            .numberValue(new BigDecimal("0.12"))
            .unit("x10*9/L");

    List<SubjectDao> subjects = subjectRepository.findAll();
    assertEquals(2, subjects.size());
    assertEquals(sub1, subjects.get(0));
    assertEquals(sub2, subjects.get(1));

    List<EncounterDao> encounters = encounterRepository.findAll();
    assertEquals(2, encounters.size());
    assertEquals(enc1, encounters.get(0));
    assertEquals(enc2, encounters.get(1));

    List<SubjectResourceDao> resources = subjectResourceRepository.findAll();
    System.out.println(resources.get(0));
    System.out.println(resources.get(1));
    assertEquals(2, resources.size());
    assertEquals(res1, resources.get(0));
    assertEquals(res2, resources.get(1));
  }
}
